SUPABASE_URL = "https://whredatvonyqirqlsugp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndocmVkYXR2b255cWlycWxzdWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjQ3NTgsImV4cCI6MjA2OTE0MDc1OH0.iuoYjRuT2x7BikgYYosdUdsCLgMBGmsANku_sqDjqV0"
